M48
; DRILL file {KiCad 7.0.6} date Mon Aug  7 22:51:57 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-07T22:51:57+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X139.065Y-67.31
X139.065Y-102.235
X203.835Y-62.23
X203.835Y-93.98
T0
M30
